services:
  frontend:
    container_name: frontend
    build: services/frontend
    develop:
      watch:
        - action: sync
          path: ./services/frontend
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
  backend:
    depends_on:
      - postgres
    container_name: backend
    build: services/backend
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./services/backend
          target: /app
          ignore:
            - Dockerfile
  postgres:
    image: postgres:14
    container_name: database
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  proxy:
    depends_on:
      - frontend
      - backend
    container_name: proxy
    build: services/proxy
    ports:
      - 8080:443
