services:
  frontend:
    container_name: frontend
    build: services/frontend
    develop:
      watch:
        - action: sync
          path: ./services/frontend
          target: /app
          ignore:
            - node_modules/
            - Dockerfile
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    container_name: backend
    build: services/backend
    develop:
      watch:
        - action: sync
          path: ./services/backend
          target: /app
          ignore:
            - Dockerfile
  postgres:
    image: postgres:14
    container_name: database
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 0.2s
  proxy:
    depends_on:
      - frontend
      - backend
    container_name: proxy
    build: services/proxy
    ports:
      - 8080:443
volumes:
  postgres_data:
    driver: local
