services:
  frontend:
    container_name: frontend
    build: services/frontend
    volumes:
      - ./services/frontend:/app
    ports:
      - 8080:5173
    networks:
      - default
  users:
    container_name: users
    build: services/users
    volumes:
      - ./services/users/:/app
    ports:
      - 8000:8000
  postgres:
    image: postgres:14
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

networks:
  default:
    driver: bridge
