services:
  frontend:
    container_name: frontend
    build: services/frontend
    volumes:
      - ./services/frontend:/app
    ports:
      - 5173:5173
    networks:
      - default

networks:
  default:
    driver: bridge
